FROM python:3.6.5-slim
RUN apt-get update && apt-get autoclean -y && pip install --no-cache-dir --upgrade pip
LABEL metadata="The base image for flask web server" \
      version=0.1.0 \
      maintainer="Volodymyr Yahello <vjagello93@gmail.com>"
