FROM vyahello/flask-blog-base:0.1.0
LABEL metadata="Main image for a flask blog" \
      version=1.0.0 \
      maintainer="Volodymyr Yahello <vjagello93@gmail.com>"
WORKDIR blog/
COPY server server
COPY requirements-blog.txt blog.py ./
RUN pip install --no-cache-dir -r requirements-blog.txt && \
    rm requirements-blog.txt
ENTRYPOINT python blog.py
